### PR TITLE
Handle "noWindow" apps

### PR DESCRIPTION
**Pull request by Tofee**
Treat them like apps the are launched hidden.

Signed-off-by: Christophe Chapuis <chris.chapuis@gmail.com>

### CODE REVIEW

**Comment by Herrie82** [comment]
@tofee was this tested now?

**Comment by Tofee** [comment]
Yes, and it doesn't seem to work as intended :( So I'll do more testing, and see where I should amend the fix

**Comment by Herrie82** [comment]
OK marked it WIP for now then

**Comment by Tofee** [comment]
This is now ready for merge

**Pull request merged**
